//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupLog
    {
        public int Id { get; set; }
        public string DatabaseName { get; set; }
        public Nullable<System.DateTime> BackupDate { get; set; }
        public string Status { get; set; }
    }
}
