//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteJuridico
    {
        public int Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public string NIT { get; set; }
        public string NroPadron { get; set; }
        public string RepresentanteLegal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
