//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public int Id { get; set; }
        public string Clausula { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<decimal> VolumenActividad { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
