//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancaria
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdEntidadFinanciera { get; set; }
        public string NroCuenta { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public Nullable<int> IdTipoCuenta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EntidadFinanciera EntidadFinanciera { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual TipoCuenta TipoCuenta { get; set; }
    }
}
