//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSistemadeInformacionIINoviembre2024Entities : DbContext
    {
        public dbSistemadeInformacionIINoviembre2024Entities()
            : base("name=dbSistemadeInformacionIINoviembre2024Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutorizacionCombustible> AutorizacionCombustible { get; set; }
        public virtual DbSet<AutorizacionSustancia> AutorizacionSustancia { get; set; }
        public virtual DbSet<BackupLog> BackupLog { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<ClienteJuridico> ClienteJuridico { get; set; }
        public virtual DbSet<ClienteNatural> ClienteNatural { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<CuentaBancaria> CuentaBancaria { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<EntidadFinanciera> EntidadFinanciera { get; set; }
        public virtual DbSet<EntidadReguladora> EntidadReguladora { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<PlanPago> PlanPago { get; set; }
        public virtual DbSet<SeguimientoTramite> SeguimientoTramite { get; set; }
        public virtual DbSet<SustanciaControlada> SustanciaControlada { get; set; }
        public virtual DbSet<TipoCuenta> TipoCuenta { get; set; }
        public virtual DbSet<TipoTramite> TipoTramite { get; set; }
        public virtual DbSet<Tramite> Tramite { get; set; }
        public virtual DbSet<TramiteCombustible> TramiteCombustible { get; set; }
        public virtual DbSet<TramiteSustancia> TramiteSustancia { get; set; }
    }
}
