//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int Id { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdPlanPago { get; set; }
        public Nullable<int> IdMoneda { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual PlanPago PlanPago { get; set; }
    }
}
